data:
  raw_path: data/raw
  processed_path: data/processed
  additional_datasets_path: data/raw/additional_datasets

model:
  xgboost:
    learning_rate: 0.1
    n_estimators: 100
    max_depth: 5
    # Add other hyperparameters here

paths:
  results: results
  figures: results/figures
  eda_results: results/EDA_results
  eda_plots: results/figures/eda_plots
  xgboost_results: results/one_vs_all/xgboost_results
  # Add paths to other directories if needed
